### ISSUE TITLE
Variables for Vampire not working on V2-1200

### ISSUE THREAD

**Issue by djbase78** [larsonmars/sysvars#10]
Seems I have some problems getting these

```
-$VampireType:      The type of vampire installed, for example "V2_600", or "V4_Standalone"
- $VampireCoreRev:   The core revision of the currently flashed firmware .jic file; "N/A", if not available (e.g., some beta cores)
- $VampireClockMult: The vampire clock multiplier
```
to work on my Vampire 1200 (Core 2.17) as they do not report anything. They are working fine on V4_Standalone.

**Comment by larsonmars** [comment]
Thank you for reporting!

You say they do not report anything, so I take it you mean they are not set. Could you verify that your $CPU variable is "68080" and $Chipset is "SAGA"? Because detecting the 68080 and SAGA is a precondition for sysvars in its current version to even consider querying the mentioned variables.

**Comment by larsonmars** [comment]
Well then this is the culprit... I thought it always has 68080 and SAGA. Then I'm gonna stick with 68080 as a base for Vampire detection...
I will  prepare a new release.
